name: Hello World

on:
  push:
   branches:
   - main

jobs:
  hello-world:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      run: actions/checkout@v4
      
    - name: Display hello world
      run: echo "Hello, world!"
 
